/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef CHUNK_KDA_BWD_INTRA_TILING_KEY_H
#define CHUNK_KDA_BWD_INTRA_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define CHUNK_KDA_BWD_INTRA_K64 0
#define CHUNK_KDA_BWD_INTRA_K128 1
#define CHUNK_KDA_BWD_INTRA_K256 2
#define CHUNK_KDA_BWD_INTRA_SAFE 1
#define CHUNK_KDA_BWD_INTRA_UNSAFE 0
#define CHUNK_KDA_BWD_INTRA_DENSE_BNSD 0
#define CHUNK_KDA_BWD_INTRA_VARLEN_TND 1

ASCENDC_TPL_ARGS_DECL(
    ChunkKdaBwdIntra,
    ASCENDC_TPL_UINT_DECL(K_KEY, 2, ASCENDC_TPL_UI_LIST,
                          CHUNK_KDA_BWD_INTRA_K64, CHUNK_KDA_BWD_INTRA_K128,
                          CHUNK_KDA_BWD_INTRA_K256),
    ASCENDC_TPL_UINT_DECL(SAFE_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_KDA_BWD_INTRA_UNSAFE, CHUNK_KDA_BWD_INTRA_SAFE),
    ASCENDC_TPL_UINT_DECL(LAYOUT_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_KDA_BWD_INTRA_DENSE_BNSD, CHUNK_KDA_BWD_INTRA_VARLEN_TND)
);

#define CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY(K, SAFE, LAYOUT)                                  \
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(K_KEY, ASCENDC_TPL_UI_LIST, K),                \
                         ASCENDC_TPL_UINT_SEL(SAFE_KEY, ASCENDC_TPL_UI_LIST, SAFE),            \
                         ASCENDC_TPL_UINT_SEL(LAYOUT_KEY, ASCENDC_TPL_UI_LIST, LAYOUT))

ASCENDC_TPL_SEL(
    CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY(
        CHUNK_KDA_BWD_INTRA_K64, CHUNK_KDA_BWD_INTRA_SAFE, CHUNK_KDA_BWD_INTRA_DENSE_BNSD),
    CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY(
        CHUNK_KDA_BWD_INTRA_K128, CHUNK_KDA_BWD_INTRA_SAFE, CHUNK_KDA_BWD_INTRA_DENSE_BNSD),
    CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY(
        CHUNK_KDA_BWD_INTRA_K256, CHUNK_KDA_BWD_INTRA_SAFE, CHUNK_KDA_BWD_INTRA_DENSE_BNSD),
    CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY(
        CHUNK_KDA_BWD_INTRA_K128, CHUNK_KDA_BWD_INTRA_SAFE, CHUNK_KDA_BWD_INTRA_VARLEN_TND)
);

#undef CHUNK_KDA_BWD_INTRA_TPL_SEL_ENTRY

#endif // CHUNK_KDA_BWD_INTRA_TILING_KEY_H
